<option <?php if ($startHour == "01") { echo 'selected'; } ?>>01</option>
<option <?php if ($startHour == "02") { echo 'selected'; } ?>>02</option>
<option <?php if ($startHour == "03") { echo 'selected'; } ?>>03</option>
<option <?php if ($startHour == "04") { echo 'selected'; } ?>>04</option>
<option <?php if ($startHour == "05") { echo 'selected'; } ?>>05</option>
<option <?php if ($startHour == "06") { echo 'selected'; } ?>>06</option>
<option <?php if ($startHour == "07") { echo 'selected'; } ?>>07</option>
<option <?php if ($startHour == "08") { echo 'selected'; } ?>>08</option>
<option <?php if ($startHour == "09") { echo 'selected'; } ?>>09</option>
<option <?php if ($startHour == "10") { echo 'selected'; } ?>>10</option>
<option <?php if ($startHour == "11") { echo 'selected'; } ?>>11</option>
<option <?php if ($startHour == "12") { echo 'selected'; } ?>>12</option>
